-- Désactiver les contraintes de clés étrangères
ALTER TABLE details_vente DISABLE TRIGGER ALL;
ALTER TABLE details_achat DISABLE TRIGGER ALL;
ALTER TABLE recette DISABLE TRIGGER ALL;
ALTER TABLE fabrication DISABLE TRIGGER ALL;
ALTER TABLE mvt_stock_ingredient DISABLE TRIGGER ALL;
ALTER TABLE mvt_stock_produit DISABLE TRIGGER ALL;
ALTER TABLE ventes DISABLE TRIGGER ALL;
ALTER TABLE achats DISABLE TRIGGER ALL;
ALTER TABLE produits DISABLE TRIGGER ALL;
ALTER TABLE categories DISABLE TRIGGER ALL;
ALTER TABLE produits_categories DISABLE TRIGGER ALL;
ALTER TABLE garnitures DISABLE TRIGGER ALL;
ALTER TABLE produits_garnitures DISABLE TRIGGER ALL;
ALTER TABLE ingredients DISABLE TRIGGER ALL;
ALTER TABLE unites DISABLE TRIGGER ALL;
ALTER TABLE clients DISABLE TRIGGER ALL;
ALTER TABLE fournisseurs DISABLE TRIGGER ALL;

-- Supprimer les données de chaque table
TRUNCATE TABLE details_vente CASCADE;
TRUNCATE TABLE details_achat CASCADE;
TRUNCATE TABLE recette CASCADE;
TRUNCATE TABLE fabrication CASCADE;
TRUNCATE TABLE mvt_stock_ingredient CASCADE;
TRUNCATE TABLE mvt_stock_produit CASCADE;
TRUNCATE TABLE ventes CASCADE;
TRUNCATE TABLE achats CASCADE;
TRUNCATE TABLE produits CASCADE;
TRUNCATE TABLE categories CASCADE;
TRUNCATE TABLE garnitures CASCADE;
TRUNCATE TABLE produits_categories;
TRUNCATE TABLE produits_garnitures;
TRUNCATE TABLE ingredients CASCADE;
TRUNCATE TABLE unites CASCADE;
TRUNCATE TABLE clients CASCADE;
TRUNCATE TABLE fournisseurs CASCADE;

-- INSERTIONS ICI

-- Réinitialiser les séquences d'incrémentation
ALTER SEQUENCE unites_id_seq RESTART WITH 1;
ALTER SEQUENCE ingredients_id_seq RESTART WITH 1;
ALTER SEQUENCE produits_id_seq RESTART WITH 1;
ALTER SEQUENCE categories_id_seq RESTART WITH 1;
ALTER SEQUENCE garnitures_id_seq RESTART WITH 1;
ALTER SEQUENCE mvt_stock_ingredient_id_seq RESTART WITH 1;
ALTER SEQUENCE mvt_stock_produit_id_seq RESTART WITH 1;
ALTER SEQUENCE fabrication_id_seq RESTART WITH 1;
ALTER SEQUENCE clients_id_seq RESTART WITH 1;
ALTER SEQUENCE fournisseurs_id_seq RESTART WITH 1;
ALTER SEQUENCE ventes_id_seq RESTART WITH 1;
ALTER SEQUENCE details_vente_id_seq RESTART WITH 1;
ALTER SEQUENCE achats_id_seq RESTART WITH 1;
ALTER SEQUENCE details_achat_id_seq RESTART WITH 1;

-- Réactiver les contraintes de clés étrangères
ALTER TABLE details_vente ENABLE TRIGGER ALL;
ALTER TABLE details_achat ENABLE TRIGGER ALL;
ALTER TABLE recette ENABLE TRIGGER ALL;
ALTER TABLE fabrication ENABLE TRIGGER ALL;
ALTER TABLE mvt_stock_ingredient ENABLE TRIGGER ALL;
ALTER TABLE mvt_stock_produit ENABLE TRIGGER ALL;
ALTER TABLE ventes ENABLE TRIGGER ALL;
ALTER TABLE achats ENABLE TRIGGER ALL;
ALTER TABLE produits ENABLE TRIGGER ALL;
ALTER TABLE categories ENABLE TRIGGER ALL;
ALTER TABLE produits_categories ENABLE TRIGGER ALL;
ALTER TABLE garnitures ENABLE TRIGGER ALL;
ALTER TABLE produits_garnitures ENABLE TRIGGER ALL;
ALTER TABLE ingredients ENABLE TRIGGER ALL;
ALTER TABLE unites ENABLE TRIGGER ALL;
ALTER TABLE clients ENABLE TRIGGER ALL;
ALTER TABLE fournisseurs ENABLE TRIGGER ALL;
